POST  http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "ds@gmail.com",
    "password": "1234567899900"
}


###

POST  http://localhost:3000/auth/create HTTP/1.1
content-type: application/json

{
    "firstName": "ds",
    "lastName": "ds",
    "phoneNumber": "+2349090604823",
    "email": "ds@gmail.com",
    "password": "1234567899900"
}

###

GET http://localhost:3000/auth/profile HTTP/1.1




###

POST  http://localhost:3000/ticket/create HTTP/1.1
content-type: application/json

{
  "firstName": "firstName",
  "lastName": "LastName",
  "trainName": "EuroStar",
  "trainNumber": "3924",
  "depatureStation": "Abeokuta",
  "arrivalStation": "Kano",
  "ticketReferenceNumber": "T4-04592963154",
  "seatNumber": "A18",
  "price": "# 7,500.00",
  "bookingStatus": "Success",
  "trainServiceType": "Business"
}


###

GET http://localhost:3000/ticket/ HTTP/1.1


###

GET http://localhost:3000/ticket/:id HTTP/1.1


###

DELETE http://localhost:3000/ticket/:id HTTP/1.1


###

PUT http://localhost:3000/ticket/:id HTTP/1.1

{
  "firstName": "firstName",
  "lastName": "LastName",
  "trainName": "EuroStar",
  "trainNumber": "3924",
  "depatureStation": "Abeokuta",
  "arrivalStation": "Kano",
  "ticketReferenceNumber": "T4-04592963154",
  "seatNumber": "A18",
  "price": "# 7,500.00",
  "bookingStatus": "Success",
  "trainServiceType": "Business"
}



###

POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}



